name: Spawn
version: "1.0"
author: THEZAK
api: ["1.0.0"]
main: cz.THEZAK.Essentials.Main
commands:
  spawn:
    description: Teleport you to spawn
    permission: essentials.spawn
  setspawn:
    description: Set spawn location
    permission: essentials.setspawn
  setwarp:
    description: Set warp
    permission: essentials.setwarp 
